eclipse-platform/eclipse.platform.debug

- org.eclipse.debug.tests/src/org/eclipse/debug/tests/console/IOConsoleTests.java
java.lang.AssertionError: Test triggered errors in IOConsole: Status ERROR: org.eclipse.debug.tests code=0 [testBug421303_StreamProcessingDeadlock] Some job is still running or waiting to run: 
'Animation start(41)'/org.eclipse.ui.internal.progress.TaskBarProgressManager$1
thread info: "Worker-11" prio=5 Id=64 TIMED_WAITING on org.eclipse.core.internal.jobs.WorkerPool@7910e307
at java.base@11.0.10/java.lang.Object.wait(Native Method)
-  waiting on org.eclipse.core.internal.jobs.WorkerPool@7910e307
at org.eclipse.core.internal.jobs.WorkerPool.sleep(WorkerPool.java:200)
at org.eclipse.core.internal.jobs.WorkerPool.startJob(WorkerPool.java:242)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:58)
instead of
java.lang.AssertionError: Test triggered errors in IOConsole: …
> improve error msg for testBug421303_StreamProcessingDeadlock #5

- org.eclipse.debug.tests/src/org/eclipse/debug/tests/TestUtil.java
- org.eclipse.debug.tests/src/org/eclipse/debug/tests/console/IOConsoleTestUtil.java
wait 10 sec instead of 5 times 2sec. The logged error after 3sec was
reported on teardown() even when 10sec have not yet passed.
> fix testBug421303_StreamProcessingDeadlock failure on Windows #5

- org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/launchConfigurations/ShowCommandLineDialog.java
Exception was silently put to System.err
for example when StringSubstitutionEngine failed to resolve undefined
variable.
> Log exceptions in ShowCommandLine

- org.eclipse.debug.tests/src/org/eclipse/debug/tests/console/RuntimeProcessTests.java
JUnit asserts give better messages and is simpler to read/understand.
> No need to use complicated hamcrest asserts.

- org.eclipse.debug.examples.memory/pom.xml
- org.eclipse.debug.examples.mixedmode/pom.xml
- org.eclipse.debug.tests/pom.xml
- org.eclipse.debug.ui.launchview.tests/pom.xml
- org.eclipse.debug.ui.launchview/pom.xml
- org.eclipse.debug.ui/pom.xml
- org.eclipse.unittest.ui/pom.xml
- pom.xml
Tracked in [eclipse.platform.releng.aggregator#290](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/290) and [eclipse.platform.releng.aggregator#291](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/291)
Need to wait to merge until after 4.24 Release
> WIP: POM and product version changes for 4.25 release

- org.eclipse.debug.ui/plugin.xml
All the "Run" and "Profile" related actions have been compared and the
missing icons were added to the "Profile as" actions.
The icon appears correctly in the "Menu visibility" configuration dialog
for the "Profile as" main menu group. The context menu has not been
tested due to no profiler available in my test runtime.
> Add icons to "Profile as" launch and context menus #19

- org.eclipse.debug.ui/plugin.xml
Looks like this after the change, when using "Open resource" in Debug perspective:
If you want to test locally, remember to reset the perspective of your test runtime to see the effect.
> Add "Show in Project Explorer" to Debug perspective

- org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/preferences/RunDebugPropertiesPage.java
The plugin.xml enables this page for objects that adapt to IResource or
to IProject. The Java code however completely misses the part for
adapting to IProject. Therefore each object that adapts to IProject but
not IResource would cause an NPE until now.
> NPE in RunDebugPropertiesPage (fixes #33)

- org.eclipse.ui.console/src/org/eclipse/ui/internal/console/ansi/preferences/AnsiConsolePreferenceConstants.java
Instead of
org.eclipse.ui.console/booleanEnabled=false
product customization file can use now
org.eclipse.ui.console/ANSI_support_enabled=false
etc
See https://github.com/eclipse-platform/eclipse.platform.debug/issues/57
> ANSI console integration: qualified preference values

- org.eclipse.ui.console/src/org/eclipse/ui/internal/console/ansi/preferences/AnsiConsolePreferencePage.java
This should address item 3 in https://github.com/eclipse-platform/eclipse.platform.debug/issues/57#issuecomment-1208323469
_"Fix enablement of the options in the preference page: if "Enable ANSI Support" is unchecked, all options below should be disabled, and vice versa."_
> Disable the preference fields if ANSI support is disabled

- org.eclipse.ui.console/src/org/eclipse/ui/internal/console/ansi/commands/EnableDisableHandler.java
Don't set preference store value from handler persistent state, that
breaks product customization support because initial value is hard coded
in plugin xml. Instead, read the initial state from store and apply to
the command state.
Fixes https://github.com/eclipse-platform/eclipse.platform.debug/issues/63
> Fix ANSI support EnableDisableHandler init

- org.eclipse.debug.ui.launchview/build.properties
> Remove org.eclipse.pde.ds.lib/annotations.jar from extra classpath

- org.eclipse.ui.console/src/org/eclipse/ui/internal/console/IConsoleHelpContextIds.java
- org.eclipse.ui.console/src/org/eclipse/ui/internal/console/ansi/preferences/AnsiConsolePreferencePage.java
The https://github.com/eclipse-platform/eclipse.platform.common/pull/60 adds a help page for the ANSI Support Preferences page:
And this PR adds the proper context IDs so that invoking the help from the preference dialog gets us to the right web page.
---
This is to address 
https://github.com/eclipse-platform/eclipse.platform.debug/issues/47#issuecomment-1206036042
> Add help context for the ANSI Preferences dialog

- org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/DebugUIPlugin.java
Fixes https://github.com/eclipse-platform/.github/issues/50
> Don't use getActiveWorkbenchWindow() which can be null

- org.eclipse.debug.ui/ui/org/eclipse/debug/ui/PrototypeTab.java
- org.eclipse.debug.ui/ui/org/eclipse/debug/ui/actions/ExportBreakpointsOperation.java
- org.eclipse.debug.ui/ui/org/eclipse/debug/ui/actions/ImportBreakpointsOperation.java
As found by Java 17 javadoc tool.
Needed by
eclipse-platform/eclipse.platform.releng.aggregator#482
> Fix Javadoc warnings and errors.

- org.eclipse.debug.ui/META-INF/MANIFEST.MF
- org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/DebugUIPlugin.java
This change synchronizes access to DebugUIPlugin.fSaveParticipants, so that no CME can occur on concurrent access.
Fixes: #94
Signed-off-by: Simeon Andreev <simeon.danailov.andreev@gmail.com>
> ConcurrentModificationException in DebugUIPlugin$1.saving

- org.eclipse.debug.ui.launchview.tests/build.properties
- org.eclipse.debug.ui.launchview.tests/plugin.properties
They were erroneously added to the plugin.properties instead of the build.properties.
FYI @iloveeclipse, @akurtakov
> [Build] Fix Tycho-pomless properties by moving them to build.properties

- org.eclipse.debug.core/META-INF/MANIFEST.MF
- org.eclipse.debug.core/plugin.properties
- org.eclipse.debug.core/plugin.xml
The compare editor opens a binary comparison by default for .prototype files (those are launch configuration prototypes). Have a content type and text file type registration to have the text comparison opening by default.
> Register launch prototype as text file content

- org.eclipse.ui.externaltools/External Tools Base/org/eclipse/ui/externaltools/internal/ui/ExternalToolsUIMessages.java
- org.eclipse.ui.externaltools/META-INF/MANIFEST.MF
Removed three unused keys that starts from
`ExternalToolsPreferencePage_`
Signed-off-by: Alexander Fedorov <alexander.fedorov@arsysop.ru>
> Remove unused keys from ExternalToolsUIMessages #102

- org.eclipse.debug.ui/ui/org/eclipse/debug/ui/actions/AbstractLaunchHistoryAction.java
Leverages "Display implements Executor".
See https://github.com/eclipse-platform/eclipse.platform.swt/pull/67
> Use Display as Executor in future

- org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/launchConfigurations/ExportLaunchConfigurationAction.java
Don't take the workbench window for opening new dialogs. This leads to blocked UI if a modal dialog gets triggered from another modal dialog. Since the action itself knows its shell, that one is a better solution.
> Use current shell for nested modal dialogs, fixes #110

- org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/actions/LaunchShortcutAction.java
- org.eclipse.debug.ui/ui/org/eclipse/debug/ui/actions/ContextualLaunchAction.java
Currently ILaunchShortcut2 is only queried for the launch button but not when one uses the context menu, this adds expanding the items from a ILaunchShortcut2 to be added to the Run As / Debug As / ... menus.
FYI @mickaelistria 
This is related to
- https://github.com/eclipse-m2e/m2e-core/pull/1309
> Expand launches provided by ILaunchShortcut2

- org.eclipse.debug.ui/ui/org/eclipse/debug/ui/actions/ContextualLaunchAction.java
When the shortcut refers to no specific launch configuration and returns an empty array, show the shortcut as usual.
> Run context menu missing some entries

- org.eclipse.debug.ui.launchview/META-INF/MANIFEST.MF
- Always use closed version ranges [1.X,2) with a minor lower bound
- Mark package-import that is not optional as such
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056
> Improve OSGi metadata about dependency to javax.inject/annotations

- org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/views/memory/renderings/AsyncTableRenderingViewer.java
Make memory view cell editor visible on Linux GTK3 #132
Since SWT change from GTK2 to GTK3 as its backend the cell
editing in the memory view has not worked properly
with the cell editor not visible. This change uses explicit
setVisible rather than adjusting Z-order of the controls.
Fixes https://github.com/eclipse-platform/eclipse.platform.debug/issues/132
> Make memory view cell editor visible on Linux GTK3 #132

- org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/SWTFactory.java
- org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/launchConfigurations/LaunchConfigurationView.java
The text widget in both run and debug configurations follow the sashing only partially - at some point, the filter text overlays into the neighboring areas. this is because of the conflicting layoutdata property defined for the text and the label controls in the parent composite. if grabExcessHorizontalSpace property is set to true for one and false for another child controls, the layout gets convoluted, or follow only one of the request.
The issue is there in Windows as well but not visible due to the absence of focus ring. The issue was due to not grabbing the horizontal space for the Label attached to the bottom of the composite area. Making the grabExcessHorizontalSpace variable of GridData to true resolves the issue.
Fix is to force the same flag in both the cases leading to properly …
> Properly resize Launch configuration controls

- org.eclipse.debug.ui/ui/org/eclipse/debug/ui/actions/ContextualLaunchAction.java
In some cases, the launch shortcut behavior is still desired and the substitute launch config doesn't match this behavior (this might be considered as a bug from the shortcut implementation, yet it's still an important case that we can handle in the framework). To avoid loosing functionality, we show the shortcut "as usual" and then the launch configs that the shortcut may reference.
Fixes https://github.com/eclipse-platform/eclipse.platform.debug/issues/135
> Launch shortcut to show action then configs

- org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/views/variables/details/DetailPaneManager.java
Avoiding type-casts makes code easier to read.
> Use typed for-each loop

- org.eclipse.debug.ui/ui/org/eclipse/debug/internal/ui/groups/GroupLaunchConfigurationTabGroup.java
> GroupLaunchConfigurationTabGroup: remove dead code

- org.eclipse.debug.core/core/org/eclipse/debug/core/model/LaunchConfigurationDelegate.java
Adjusted the exception type caught in
`LaunchConfigurationDelegate.isLaunchProblem(IMarker)`, to match the thrown `ResourceException`.
Fixes: #136
> Marker id ... not found when launching debuggee Eclipse
